### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by SandeepPadhi** [User1m/votingdapptut#3]
I followed as instructed,but it is showing error as below:
Please resolve the issue.Thankyou in advance.
root@sandeep-Vostro-3558:~/Blockchain_prax/votingdapp# npm start

> votingdapp@1.0.0 start /home/sandeep/Blockchain_prax/votingdapp
> node deployContract.js && http-server .

------------ LOGGING ACCOUNTS -------------

[ '0x443f6a5482ef9844edfe48ced57f5ee587699170',
  '0xea69788962c9b1f063bc70e499cca810684b5526',
  '0xc5aa7714c1759ca05efc0454b88114da6b6e9d3d',
  '0x88a7d9b6f310920f68dae9bfde586ece1fea9d71',
  '0x8034129b9db339125d037fbc59382434c80510db',
  '0x29fccb9e187f7ecb89d9efcc04583a3e95581a77',
  '0x39570959794e886a0f735fea02f23dbfaa4d7eb9',
  '0x6525603ff9a33f65bd23d46c3191070d2e9310c8',
  '0xf00cd27cfa5f8892fe6cbb2d13291538551f0268',
  '0xd3f53da7202c737cf5e9ddb4703f783264dee847' ]
First account is 0x443f6a5482ef9844edfe48ced57f5ee587699170

------------ LOGGING COMPILED CODE -------------

{"errors":[{"component":"general","formattedMessage":"* Line 1, Column 1\n  Syntax error: value, object or array expected.\n* Line 1, Column 2\n  Extra non-whitespace after JSON value.\n","message":"* Line 1, Column 1\n  Syntax error: value, object or array expected.\n* Line 1, Column 2\n  Extra non-whitespace after JSON value.\n","severity":"error","type":"JSONError"}]}
/home/sandeep/Blockchain_prax/votingdapp/deployContract.js:18
var byteCode = compiledCode.contracts[":Voting"].bytecode;
                                     ^

TypeError: Cannot read property ':Voting' of undefined
    at Object.<anonymous> (/home/sandeep/Blockchain_prax/votingdapp/deployContract.js:18:38)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! votingdapp@1.0.0 start: `node deployContract.js && http-server .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the votingdapp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sandeep/.npm/_logs/2018-12-28T07_37_55_359Z-debug.log
root@sandeep-Vostro-3558:~/Blockchain_prax/votingdapp#

**Comment by SandeepPadhi** [comment]
On remix it compiles perfectly,but it doesnot on local solidity compiler

**Comment by SandeepPadhi** [comment]
After compiling on remix ,I copied bytecode and ABI and added it to the deployContracts.js code .
when I do npm start ,I get following error:
Error: VM Exception while processing transaction: out of gas
    at Object.InvalidResponse (/home/sandeep/Blockchain_prax/votingdapp/node_modules/web3/lib/web3/errors.js:38:16)
    at /home/sandeep/Blockchain_prax/votingdapp/node_modules/web3/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/home/sandeep/Blockchain_prax/votingdapp/node_modules/web3/lib/web3/httpprovider.js:122:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/sandeep/Blockchain_prax/votingdapp/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/sandeep/Blockchain_prax/votingdapp/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/sandeep/Blockchain_prax/votingdapp/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/sandeep/Blockchain_prax/votingdapp/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

I am a newbie in Ethereum development.Your help will be really appreciated as I have tried all sites on google but couldnt resolve it .
Thankyou in advance
